language: c

matrix:
    include:
        - os: linux
          dist: trusty

script:
    - git remote add upstream https://github.com/KhronosGroup/EGL-Registry.git
    - git fetch upstream
    - git diff-tree --exit-code -p ..upstream/master api/egl.xml
